version: "2"

services:
  web:
    image: ksealey1990/ubuntu-18-laravel:08-14-2019
    restart: always
    container_name: mf_web
    ports: 
      - "80:80"
    networks:
      - mf_net
    volumes: 
      - "/Users/ksealey1990/MarketFlows-API:/var/www/app"
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal
    expose:
      - "9000"
  db:
    image: mysql:5.7.22
    restart: always
    container_name: mf_mysql
    environment:
      - MYSQL_DATABASE=mf
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mf_net
  nosql_a:
    image: cassandra:latest
    restart: always
    container_name: mf_nosql_a
    networks:
      - mf_net
  nosql_b:
    image: cassandra:latest
    restart: always
    container_name: mf_nosql_b
    environment: # tell the second where the first is
      - CASSANDRA_SEEDS=mf_nosql_a
    networks:
      - mf_net
networks:
  mf_net: