version: "2"

services:
  mf_app_web:
    image: 212127452432.dkr.ecr.us-east-1.amazonaws.com/marketflows-api:latest
    restart: always
    container_name: mf_app_web
    ports: 
      - "80:80"
    networks:
      - mf_net
    volumes: 
      - "$APP_PATH:/var/www/app"
    environment:
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal
  mf_app_db:
    image: mysql:5.7.22
    restart: always
    container_name: mf_app_db
    environment:
      - MYSQL_DATABASE=marketflows
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mf_net
networks:
  mf_net: