version: "2"

services:
  mf_app_web:
    image: marketflows/ubuntu18-php7:latest
    restart: always
    container_name: mf_app_web
    ports: 
      - "80:80"
      - "9515:9515"
    networks:
      - mf_net
    volumes: 
      - "$APP_PATH:/var/www/app"
      - "$APP_PATH/build/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
  mf_app_db:
    image: mysql:5.7.22
    restart: always
    container_name: mf_app_db
    environment:
      - MYSQL_DATABASE=marketflows
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - mf_net
  mf_app_cache:
    image: redis:latest
    restart: always
    container_name: mf_app_cache
    ports: 
      - "6379:6379"
    networks:
      - mf_net
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mf_net
networks:
  mf_net: